# Production Profile
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Production Security (Inject via Environment Variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}